### ISSUE TITLE
ping 不通

### ISSUE THREAD

**Issue by zhipfang** [liyupi/yuindex#35]
ping baidu.com
errorping 不通！
ping www.baidu.com
errorping 不通！

**Comment by BabyLy233** [comment]
这个问题我也发现了，network控制台可以看见是 GET 请求 URL: https://www.yuindex.com/www.baidu.com
必须带协议写成 ping https://www.baidu.com

**Comment by gaoquanhui** [comment]
其实ping https://www（我没写错）也能ping通.只要加上https后面随便写都可以ping通过

**Comment by LuruiminF** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
