### ISSUE TITLE
abnormal display

### ISSUE THREAD

**Issue by yuameshi** [liyupi/yuindex#39]
rt
![Screenshot_2022-07-28-13-25-48-704_com microsoft emmx](https://user-images.githubusercontent.com/64469437/181427438-b5c5ae4a-e0d4-4246-b4c6-b46faf1dca80.jpg)

**Comment by yuameshi** [comment]
呃呃，项目都被vc删了（

**Comment by LuruiminF** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
