### ISSUE TITLE
希望能够添加SSH连接功能

### ISSUE THREAD

**Issue by Torther** [liyupi/yuindex#8]

**Comment by liyupi** [comment]
其实最开始是打算用 xterm.js 来作为终端的，它能够很轻松地实现 ssh。
但对我现在这个自实现终端来说，可能会有一些成本，可以试试，我觉得实现了会很酷。

**Comment by Torther** [comment]
> 其实最开始是打算用 xterm.js 来作为终端的，它能够很轻松地实现 ssh。 但对我现在这个自实现终端来说，可能会有一些成本，可以试试，我觉得实现了会很酷。

非常期待

**Comment by LuruiminF** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
