### ISSUE TITLE
鱼皮，鱼皮如何修改默认的欢迎语？

### ISSUE THREAD

**Issue by IAMZINT** [liyupi/yuindex#88]
我想要修改欢迎语，但我找不到配置文件。

**Comment by wushiwe-beep** [comment]
YuTerminal.vue 407行作业

**Comment by wushiwe-beep** [comment]
YuTerminal.vue 407行左右

**Comment by LuruiminF** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
